[phases.setup]
nixPkgs = ["python3", "chromium"]

[phases.install]
cmds = ["python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"]

[phases.start]
cmd = "streamlit run app.py --server.port=$PORT --server.address=0.0.0.0" 